# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('emailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='title',
            field=models.CharField(choices=[], max_length=255, verbose_name='template'),
        ),
    ]
